using zachtbeer.SqlSchemaHasher;
using Shouldly;

namespace SqlSchemaHash.IntegrationTests.Settings;

/// <summary>
/// TESTPLAN §C P2 — <see cref="ConstraintNormalization.NormalizeAutoGeneratedNames"/> must stay
/// stable across a script-out / DACPAC redeploy.
///
/// <c>is_system_named</c> is recorded at CREATE time from whether the statement supplied a name, so a
/// system-named constraint that is scripted out (SSMS emits its literal generated name) and recreated
/// reads <c>is_system_named = 0</c> on the copy — the flag flips even though the name is still an
/// obvious generated one. Relying on the flag alone would report a spurious difference between the two
/// environments, so <c>NormalizeAutoGeneratedNames</c> collapses a name when the flag is set OR the
/// name matches the generated shape.
/// </summary>
[TestClass]
public class AutoGeneratedNameResilienceTests : MatrixTestBase
{
    // A literal, system-shaped PK name of the form SQL Server would mint (16-hex suffix). Supplying it
    // explicitly reproduces exactly what a script-out + recreate produces: the same-looking name, but
    // is_system_named = 0.
    private const string ScriptedSystemName = "PK__T__3214EC0700000000";

    [TestMethod]
    public async Task IsSystemNamed_FlipsWhenScriptedWithLiteralName()
    {
        // Evidence for the whole premise: the catalog flag is not durable across a script-out boundary.
        var fresh = await BuildSchemaAsync("isnFresh", "CREATE TABLE dbo.T (Id INT NOT NULL PRIMARY KEY)");
        var scripted = await BuildSchemaAsync("isnScripted", $"CREATE TABLE dbo.T (Id INT NOT NULL CONSTRAINT [{ScriptedSystemName}] PRIMARY KEY)");

        var freshPk = fresh.Tables.Single(t => t.Name == "T").KeyConstraints.Single();
        var scriptedPk = scripted.Tables.Single(t => t.Name == "T").KeyConstraints.Single();

        freshPk.IsSystemNamed.ShouldBeTrue("An unnamed PK is recorded as system-named");
        scriptedPk.IsSystemNamed.ShouldBeFalse("The same PK recreated from a script that supplies its literal name is recorded as NOT system-named");
    }

    [TestMethod]
    public async Task NormalizeAutoGeneratedNames_SurvivesScriptOutRename()
    {
        // source: unnamed PK (is_system_named = 1, random generated hex).
        // recreated: the scripted copy (explicit literal name, is_system_named = 0).
        var source = await BuildSchemaAsync("resSource", "CREATE TABLE dbo.T (Id INT NOT NULL PRIMARY KEY, Name NVARCHAR(50) NOT NULL)");
        var recreated = await BuildSchemaAsync("resRecreated", $"CREATE TABLE dbo.T (Id INT NOT NULL CONSTRAINT [{ScriptedSystemName}] PRIMARY KEY, Name NVARCHAR(50) NOT NULL)");

        var normalized = new SchemaHashOptions { Constraints = ConstraintNormalization.NormalizeAutoGeneratedNames, Indexes = IndexNormalization.NormalizeAutoGeneratedNames };

        Hash(source, Strict).ShouldNotBe(Hash(recreated, Strict), "Under Strict the two literal names differ");
        Hash(source, normalized).ShouldBe(Hash(recreated, normalized),
            "NormalizeAutoGeneratedNames must collapse a system-shaped name even when is_system_named has flipped to 0 across a script-out");
    }

    [TestMethod]
    public async Task NormalizeAutoGeneratedNames_ExplicitNonShapedName_StaysDistinct()
    {
        // Over-collapse guard: a genuinely explicit, non-generated name must NOT be collapsed, so a
        // table with a real constraint name stays distinct from one with a system-named constraint.
        var systemNamed = await BuildSchemaAsync("distSys", "CREATE TABLE dbo.T (Id INT NOT NULL PRIMARY KEY, Name NVARCHAR(50) NOT NULL)");
        var explicitlyNamed = await BuildSchemaAsync("distExplicit", "CREATE TABLE dbo.T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY, Name NVARCHAR(50) NOT NULL)");

        var normalized = new SchemaHashOptions { Constraints = ConstraintNormalization.NormalizeAutoGeneratedNames, Indexes = IndexNormalization.NormalizeAutoGeneratedNames };

        Hash(systemNamed, normalized).ShouldNotBe(Hash(explicitlyNamed, normalized),
            "A real (non-shaped) constraint name must survive normalization and stay distinct from a system-named one");
    }
}
