using zachtbeer.SqlSchemaHasher;
using Shouldly;

namespace SqlSchemaHash.IntegrationTests.Settings;

/// <summary>
/// TESTPLAN §C P5 — interaction sanity. Guards against a maximally-loose options object collapsing
/// the hash to a near-constant, and confirms that bits OR'd within one domain compose as expected
/// (each set bit removes its own distinction; an unset bit stays live).
/// </summary>
[TestClass]
public class InteractionSanityTests : MatrixTestBase
{
    /// <summary>Every loosening bit across every domain set at once — the maximal relaxation.</summary>
    private static SchemaHashOptions Everything => new()
    {
        Tables = TableNormalization.IgnoreColumnOrder | TableNormalization.IgnoreIdentitySeed | TableNormalization.IgnoreIdentityNotForReplication | TableNormalization.IgnoreTemporalRetention,
        Columns = ColumnNormalization.IgnoreCollation | ColumnNormalization.IgnoreAnsiPadding | ColumnNormalization.IgnoreDynamicDataMasking,
        Indexes = IndexNormalization.IgnoreNames | IndexNormalization.NormalizeAutoGeneratedNames | IndexNormalization.NormalizeClustering | IndexNormalization.IgnoreSortOrder | IndexNormalization.IgnoreFillFactor | IndexNormalization.IgnorePadIndex | IndexNormalization.IgnoreLockOptions | IndexNormalization.IgnoreDisabled,
        Constraints = ConstraintNormalization.IgnoreNames | ConstraintNormalization.NormalizeAutoGeneratedNames | ConstraintNormalization.IgnoreDisabled | ConstraintNormalization.IgnoreTrust | ConstraintNormalization.IgnoreNotForReplication,
        Modules = ModuleNormalization.IgnoreBodyText | ModuleNormalization.IgnoreSetOptions,
    };

    [TestMethod]
    public async Task AllBitsSet_StillDistinguishesGenuinelyDifferentSchemas()
    {
        // Object identity — table/column/procedure names — is never a loosening target, so two truly
        // different schemas must remain distinct no matter how loose the options are.
        var a = await BuildSchemaAsync("kitchenA",
            "CREATE TABLE dbo.Alpha (Id INT NOT NULL CONSTRAINT PK_A PRIMARY KEY, Name NVARCHAR(50) NOT NULL)",
            "CREATE PROCEDURE dbo.ProcA AS BEGIN SELECT 1 AS V END");
        var b = await BuildSchemaAsync("kitchenB",
            "CREATE TABLE dbo.Beta (Id INT NOT NULL CONSTRAINT PK_B PRIMARY KEY, Value INT NOT NULL)",
            "CREATE PROCEDURE dbo.ProcB AS BEGIN SELECT 1 AS V END");

        Hash(a, Everything).ShouldNotBe(Hash(b, Everything),
            "Even with every loosening bit set, genuinely different tables/columns/procedures must not collapse to the same hash");
    }

    [TestMethod]
    public async Task AllBitsSet_CollapsesEveryLoosenedFacet()
    {
        // Two databases that differ ONLY in loosened facets — constraint/index names, clustering, key
        // sort order, fill factor, collation, identity seed, procedure body and SET options — must be
        // equal under the maximal relaxation, and clearly different under Strict.
        var a = await BuildSchemaAsync("composeA",
            "CREATE TABLE dbo.T (Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_Alpha PRIMARY KEY CLUSTERED, Name NVARCHAR(50) COLLATE Latin1_General_CI_AS NOT NULL, Age INT NOT NULL CONSTRAINT CK_Alpha CHECK (Age > 0))",
            "CREATE NONCLUSTERED INDEX IX_Alpha ON dbo.T(Name DESC) WITH (FILLFACTOR = 80)",
            "SET QUOTED_IDENTIFIER OFF",
            "CREATE PROCEDURE dbo.P AS BEGIN SELECT 1 AS V END");
        var b = await BuildSchemaAsync("composeB",
            "CREATE TABLE dbo.T (Id INT IDENTITY(1000,5) NOT NULL CONSTRAINT PK_Beta PRIMARY KEY NONCLUSTERED, Name NVARCHAR(50) COLLATE Latin1_General_CS_AS NOT NULL, Age INT NOT NULL CONSTRAINT CK_Beta CHECK (Age > 0))",
            "CREATE CLUSTERED INDEX IX_Beta ON dbo.T(Name ASC) WITH (FILLFACTOR = 90)",
            "SET QUOTED_IDENTIFIER ON",
            "CREATE PROCEDURE dbo.P AS BEGIN SELECT 2 AS V END");

        Hash(a, Strict).ShouldNotBe(Hash(b, Strict), "Under Strict all these facets differ");
        Hash(a, Everything).ShouldBe(Hash(b, Everything), "Under the maximal relaxation every difference is in a loosened facet, so they must be equal");
    }

    [TestMethod]
    public async Task WithinDomainBitCombination_CollapsesEachSetBit_LeavesUnsetBitLive()
    {
        // Indexes = IgnoreFillFactor | IgnoreLockOptions collapses BOTH those facets at once, while a
        // sibling bit that is NOT set (IgnoreDisabled) still participates.
        var combo = new SchemaHashOptions { Indexes = IndexNormalization.IgnoreFillFactor | IndexNormalization.IgnoreLockOptions };
        var table = "CREATE TABLE dbo.T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY, C INT NOT NULL)";

        var baseline = await BuildSchemaAsync("comboBase", table, "CREATE INDEX IX_T_C ON dbo.T(C) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = OFF)");
        var bothLoosened = await BuildSchemaAsync("comboBoth", table, "CREATE INDEX IX_T_C ON dbo.T(C) WITH (FILLFACTOR = 90, ALLOW_PAGE_LOCKS = ON)");
        var disabled = await BuildSchemaAsync("comboDisabled", table, "CREATE INDEX IX_T_C ON dbo.T(C) WITH (FILLFACTOR = 80, ALLOW_PAGE_LOCKS = OFF)", "ALTER INDEX IX_T_C ON dbo.T DISABLE");

        Hash(baseline, combo).ShouldBe(Hash(bothLoosened, combo), "Both OR'd bits collapse together (fill factor AND lock options)");
        Hash(baseline, combo).ShouldNotBe(Hash(disabled, combo), "A bit that is NOT in the combo (IgnoreDisabled) still participates");
    }
}
