using zachtbeer.SqlSchemaHasher;
using Shouldly;

namespace SqlSchemaHash.IntegrationTests.Settings;

/// <summary>
/// TESTPLAN §C P2 — precedence between name bits, preset composition, and sort-key totality.
/// These guard the subtle, documented behaviors that a refactor would break without a compile error:
/// which bit wins when two are set, that the presets are exactly the union of their per-domain combos
/// (and no more), and that the element ordering is a total order over hashed content so the hash is
/// deterministic even when normalization collapses names.
/// </summary>
[TestClass]
public class PrecedenceAndCompositionTests : MatrixTestBase
{
    // ── 2.1  IgnoreNames wins over NormalizeAutoGeneratedNames ───────────────────────────────────

    [TestMethod]
    public async Task IgnoreNamesWinsOverNormalize_Index()
    {
        var table = "CREATE TABLE dbo.T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY, C INT NOT NULL)";
        var a = await BuildSchemaAsync("winIdxA", table, "CREATE INDEX IX_Alpha ON dbo.T(C)");
        var b = await BuildSchemaAsync("winIdxB", table, "CREATE INDEX IX_Beta ON dbo.T(C)");

        var normalizeOnly = new SchemaHashOptions { Indexes = IndexNormalization.NormalizeAutoGeneratedNames };
        var ignoreWins = new SchemaHashOptions { Indexes = IndexNormalization.IgnoreNames | IndexNormalization.NormalizeAutoGeneratedNames };

        Hash(a, normalizeOnly).ShouldNotBe(Hash(b, normalizeOnly), "NormalizeAutoGeneratedNames leaves these explicit names distinct");
        Hash(a, ignoreWins).ShouldBe(Hash(b, ignoreWins), "IgnoreNames wins: with both bits set, even explicit index names are dropped");
    }

    [TestMethod]
    public async Task IgnoreNamesWinsOverNormalize_Constraint()
    {
        var a = await BuildSchemaAsync("winCkA", "CREATE TABLE dbo.T (Id INT NOT NULL, Age INT NOT NULL CONSTRAINT CK_Alpha CHECK (Age > 0))");
        var b = await BuildSchemaAsync("winCkB", "CREATE TABLE dbo.T (Id INT NOT NULL, Age INT NOT NULL CONSTRAINT CK_Beta CHECK (Age > 0))");

        var normalizeOnly = new SchemaHashOptions { Constraints = ConstraintNormalization.NormalizeAutoGeneratedNames };
        var ignoreWins = new SchemaHashOptions { Constraints = ConstraintNormalization.IgnoreNames | ConstraintNormalization.NormalizeAutoGeneratedNames };

        Hash(a, normalizeOnly).ShouldNotBe(Hash(b, normalizeOnly), "NormalizeAutoGeneratedNames leaves these explicit names distinct");
        Hash(a, ignoreWins).ShouldBe(Hash(b, ignoreWins), "IgnoreNames wins: with both bits set, even explicit constraint names are dropped");
    }

    // ── 2.3  Index name-shape heuristic boundary (end-to-end) ────────────────────────────────────

    [TestMethod]
    public async Task NormalizeAutoGeneratedNames_Index_HexTailBoundary()
    {
        var table = "CREATE TABLE dbo.T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY, C INT NOT NULL)";
        var normalize = new SchemaHashOptions { Indexes = IndexNormalization.NormalizeAutoGeneratedNames };

        // 8-hex final segment is too short to be a generated GUID suffix ⇒ a real name, preserved.
        var shortA = await BuildSchemaAsync("hexShortA", table, "CREATE INDEX IX_Audit_Record_CAFEBABE ON dbo.T(C)");
        var shortB = await BuildSchemaAsync("hexShortB", table, "CREATE INDEX IX_Audit_Record_DEADBEEF ON dbo.T(C)");
        Hash(shortA, normalize).ShouldNotBe(Hash(shortB, normalize), "An 8-hex tail is too short to be treated as generated — real names stay distinct");

        // 16-hex final segment matches the generated-suffix shape ⇒ normalized away.
        var longA = await BuildSchemaAsync("hexLongA", table, "CREATE INDEX IX_Foo_ABC12345DEF67890 ON dbo.T(C)");
        var longB = await BuildSchemaAsync("hexLongB", table, "CREATE INDEX IX_Foo_1234567890ABCDEF ON dbo.T(C)");
        Hash(longA, normalize).ShouldBe(Hash(longB, normalize), "A 16-hex tail matches the generated shape and is normalized away");
    }

    // ── 2.4  Structural preset == union of the per-domain Structural combos ───────────────────────

    [TestMethod]
    public async Task StructuralPreset_EqualsComposedPerDomainStructural()
    {
        var schema = await BuildSchemaAsync("composeStructural",
            "CREATE TABLE dbo.T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY CLUSTERED, A INT NOT NULL, B INT NOT NULL)",
            "CREATE INDEX IX_T_AB ON dbo.T(A DESC, B ASC)");

        var composed = new SchemaHashOptions
        {
            IgnoreSysDiagramObjects = true,
            Tables = TableNormalization.Structural,
            Indexes = IndexNormalization.Structural,
            Constraints = ConstraintNormalization.Structural,
        };

        Hash(schema, SchemaHashOptions.Structural).ShouldBe(Hash(schema, composed),
            "The Structural preset must equal the union of each domain's Structural combo");
    }

    // ── 2.5  Each per-domain Structural folds exactly its member bits — no more ───────────────────

    [TestMethod]
    public async Task IndexesStructural_FoldsNameClusteringSortOrderAndPhysicalBits()
    {
        // Indexes.Structural = IgnoreNames | NormalizeClustering | IgnoreSortOrder | IgnoreFillFactor |
        // IgnorePadIndex | IgnoreLockOptions | IgnoreDisabled.
        var structural = new SchemaHashOptions { Indexes = IndexNormalization.Structural };
        var table = "CREATE TABLE dbo.T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY, C INT NOT NULL)";

        var nameA = await BuildSchemaAsync("ixsNameA", table, "CREATE INDEX IX_Alpha ON dbo.T(C)");
        var nameB = await BuildSchemaAsync("ixsNameB", table, "CREATE INDEX IX_Beta ON dbo.T(C)");
        Hash(nameA, structural).ShouldBe(Hash(nameB, structural), "Indexes.Structural folds index names");

        var ffA = await BuildSchemaAsync("ixsFfA", table, "CREATE INDEX IX_T_C ON dbo.T(C) WITH (FILLFACTOR = 80)");
        var ffB = await BuildSchemaAsync("ixsFfB", table, "CREATE INDEX IX_T_C ON dbo.T(C) WITH (FILLFACTOR = 90)");
        Hash(ffA, structural).ShouldBe(Hash(ffB, structural), "Indexes.Structural folds FILLFACTOR");
    }

    [TestMethod]
    public async Task TablesStructural_FoldsColumnOrder_NotIdentitySeed()
    {
        // Tables.Structural = IgnoreColumnOrder only.
        var structural = new SchemaHashOptions { Tables = TableNormalization.Structural };

        var orderA = await BuildSchemaAsync("tsOrderA", "CREATE TABLE dbo.T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY, A INT NOT NULL, B INT NOT NULL)");
        var orderB = await BuildSchemaAsync("tsOrderB", "CREATE TABLE dbo.T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY, B INT NOT NULL, A INT NOT NULL)");
        Hash(orderA, structural).ShouldBe(Hash(orderB, structural), "Tables.Structural folds column order");

        var seedA = await BuildSchemaAsync("tsSeedA", "CREATE TABLE dbo.T (Id INT IDENTITY(1,1) NOT NULL CONSTRAINT PK_T PRIMARY KEY, C INT NOT NULL)");
        var seedB = await BuildSchemaAsync("tsSeedB", "CREATE TABLE dbo.T (Id INT IDENTITY(1000,5) NOT NULL CONSTRAINT PK_T PRIMARY KEY, C INT NOT NULL)");
        Hash(seedA, structural).ShouldNotBe(Hash(seedB, structural), "Tables.Structural must NOT fold the identity seed/increment");
    }

    [TestMethod]
    public async Task ConstraintsStructural_FoldsNamesAndEnforcement()
    {
        // Constraints.Structural = IgnoreNames | IgnoreDisabled | IgnoreTrust | IgnoreNotForReplication.
        var structural = new SchemaHashOptions { Constraints = ConstraintNormalization.Structural };

        var nameA = await BuildSchemaAsync("csNameA", "CREATE TABLE dbo.T (Id INT NOT NULL, Age INT NOT NULL CONSTRAINT CK_Alpha CHECK (Age > 0))");
        var nameB = await BuildSchemaAsync("csNameB", "CREATE TABLE dbo.T (Id INT NOT NULL, Age INT NOT NULL CONSTRAINT CK_Beta CHECK (Age > 0))");
        Hash(nameA, structural).ShouldBe(Hash(nameB, structural), "Constraints.Structural folds constraint names");

        var trustA = await BuildSchemaAsync("csTrustA",
            "CREATE TABLE dbo.T (Id INT NOT NULL, Age INT NOT NULL)",
            "ALTER TABLE dbo.T WITH CHECK ADD CONSTRAINT CK_T_Age CHECK (Age > 0)");
        var trustB = await BuildSchemaAsync("csTrustB",
            "CREATE TABLE dbo.T (Id INT NOT NULL, Age INT NOT NULL)",
            "ALTER TABLE dbo.T WITH NOCHECK ADD CONSTRAINT CK_T_Age CHECK (Age > 0)");
        Hash(trustA, structural).ShouldBe(Hash(trustB, structural), "Constraints.Structural folds the untrusted (is_not_trusted) enforcement state");
    }

    // ── 2.6  V1 and V2 differ only by index key sort order ───────────────────────────────────────

    [TestMethod]
    public async Task V1VsV2_DifferOnlyByIndexSortOrder()
    {
        // No descending key anywhere ⇒ the sole V1/V2 difference (IgnoreSortOrder) cannot manifest.
        var asc = await BuildSchemaAsync("v1v2Asc",
            "CREATE TABLE dbo.T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY, A INT NOT NULL, B INT NOT NULL)",
            "CREATE INDEX IX_T_AB ON dbo.T(A ASC, B ASC)");
        Hash(asc, SchemaHashOptions.V1).ShouldBe(Hash(asc, SchemaHashOptions.V2), "With only ASC keys, V1 and V2 are identical");

        // A descending key ⇒ V1 (sort order ignored) and V2 (sort order compared) diverge.
        var desc = await BuildSchemaAsync("v1v2Desc",
            "CREATE TABLE dbo.T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY, A INT NOT NULL, B INT NOT NULL)",
            "CREATE INDEX IX_T_AB ON dbo.T(A DESC, B ASC)");
        Hash(desc, SchemaHashOptions.V1).ShouldNotBe(Hash(desc, SchemaHashOptions.V2), "A DESC key must make V1 and V2 diverge");
    }

    // ── 2.7  Sort-key totality: ordering breaks ties on enforcement flags when names collapse ─────

    [TestMethod]
    public async Task SortKeyTotality_CheckConstraints_DeterministicWhenNamesCollapse()
    {
        // Two CHECKs share a predicate and differ only in trust; with names ignored, the only thing
        // distinguishing them is the enforcement state, which the sort key must use. Building the same
        // logical pair in opposite creation order (and with different names) must hash identically.
        var ignoreNames = new SchemaHashOptions { Constraints = ConstraintNormalization.IgnoreNames };

        var db1 = await BuildSchemaAsync("skCk1",
            "CREATE TABLE dbo.T (Age INT NOT NULL)",
            "ALTER TABLE dbo.T WITH CHECK ADD CONSTRAINT CK_First CHECK (Age > 0)",
            "ALTER TABLE dbo.T WITH NOCHECK ADD CONSTRAINT CK_Second CHECK (Age > 0)");
        var db2 = await BuildSchemaAsync("skCk2",
            "CREATE TABLE dbo.T (Age INT NOT NULL)",
            "ALTER TABLE dbo.T WITH NOCHECK ADD CONSTRAINT CK_Alpha CHECK (Age > 0)",
            "ALTER TABLE dbo.T WITH CHECK ADD CONSTRAINT CK_Beta CHECK (Age > 0)");

        Hash(db1, ignoreNames).ShouldBe(Hash(db2, ignoreNames),
            "A trusted+untrusted CHECK pair over the same predicate must hash deterministically regardless of creation order once names are ignored");
    }

    [TestMethod]
    public async Task SortKeyTotality_ForeignKeys_DeterministicWhenNamesCollapse()
    {
        // Two FKs over the same column to the same table differ only in trust; with names ignored,
        // the enforcement flags must break the tie so the order (and hash) is deterministic.
        var ignoreNames = new SchemaHashOptions { Constraints = ConstraintNormalization.IgnoreNames };
        string[] Build(string first, string second) => new[]
        {
            "CREATE TABLE dbo.Parent (Id INT NOT NULL CONSTRAINT PK_Parent PRIMARY KEY)",
            "CREATE TABLE dbo.Child (Id INT NOT NULL CONSTRAINT PK_Child PRIMARY KEY, ParentId INT NOT NULL)",
            first,
            second,
        };

        var trusted = "ALTER TABLE dbo.Child WITH CHECK ADD CONSTRAINT {0} FOREIGN KEY (ParentId) REFERENCES dbo.Parent(Id)";
        var untrusted = "ALTER TABLE dbo.Child WITH NOCHECK ADD CONSTRAINT {0} FOREIGN KEY (ParentId) REFERENCES dbo.Parent(Id)";

        var db1 = await BuildSchemaAsync("skFk1", Build(string.Format(trusted, "FK_First"), string.Format(untrusted, "FK_Second")));
        var db2 = await BuildSchemaAsync("skFk2", Build(string.Format(untrusted, "FK_Alpha"), string.Format(trusted, "FK_Beta")));

        Hash(db1, ignoreNames).ShouldBe(Hash(db2, ignoreNames),
            "A trusted+untrusted FK pair to the same table/column must hash deterministically regardless of creation order once names are ignored");
    }
}
