using zachtbeer.SqlSchemaHasher;
using Shouldly;

namespace SqlSchemaHash.IntegrationTests.Settings;

/// <summary>
/// Unit-level preset and name-heuristic semantics that sit outside the MatrixTestBase bit-contract
/// harness: the <see cref="SchemaHashCalculator.IsAutoGeneratedName"/> name-shape rules, the
/// <c>Default</c>=<c>V2</c> preset aliasing / fresh-instance guarantee, the auto-generated constraint-
/// name normalization for an explicitly-but-system-shaped name, and that <c>ComputeHash</c> honors the
/// index sort-order option on already-extracted metadata.
/// </summary>
[TestClass]
public class PresetAndHeuristicTests : IntegrationTestBase
{
    [TestMethod]
    public void IsAutoGeneratedName_DetectsKnownFormats()
    {
        SchemaHashCalculator.IsAutoGeneratedName("PK__TableNam__3214EC07A1B2C3D4").ShouldBeTrue("SQL Server system PK name (16-hex suffix)");
        SchemaHashCalculator.IsAutoGeneratedName("DF__Tab__Col__8E1F2D3C").ShouldBeTrue("SQL Server system default constraint name (8-hex suffix)");
        SchemaHashCalculator.IsAutoGeneratedName("nci_wi_Asset_EF8A0893C0DB8B0FC4AD9EABBE187744").ShouldBeTrue("GUID-suffixed missing-index name");
        SchemaHashCalculator.IsAutoGeneratedName("PK_Assets").ShouldBeFalse("Explicit PK name");
        SchemaHashCalculator.IsAutoGeneratedName("IX_Assets_Name").ShouldBeFalse("Explicit index name");
        SchemaHashCalculator.IsAutoGeneratedName("").ShouldBeFalse("Empty name");
    }

    [TestMethod]
    public void IsAutoGeneratedName_RejectsOrdinaryNamesWithShortHexSuffix()
    {
        // Regression: the GUID heuristic must require a long (>= 16-char) hex suffix. An explicit
        // index name whose final segment is a short 8-char hex run must NOT be treated as
        // auto-generated, otherwise NormalizeAutoGeneratedIndexNames would erase a real name.
        SchemaHashCalculator.IsAutoGeneratedName("IX_Audit_Record_CAFEBABE").ShouldBeFalse("An 8-hex final segment is too short to be a generated GUID suffix and must not be normalized");
        // 16- and 32-hex generated suffixes remain detected (the established contract).
        SchemaHashCalculator.IsAutoGeneratedName("IX_Employees_Name_ABC12345DEF67890").ShouldBeTrue("A 16-hex generated suffix is auto-generated");
        SchemaHashCalculator.IsAutoGeneratedName("nci_wi_Asset_EF8A0893C0DB8B0FC4AD9EABBE187744").ShouldBeTrue("A full 32-hex GUID suffix is auto-generated");
    }

    [TestMethod]
    public async Task ConstraintName_ThatLooksSystemGenerated_IsNormalized_EvenWhenExplicitlyNamed()
    {
        // NormalizeAutoGeneratedNames treats a name as auto-generated when the catalog is_system_named
        // flag is set OR the name matches the generated shape (PK__/CK__ ... __<hex>). This is a
        // deliberate trade for deploy-resilience — the flag flips to 0 when a system-named constraint is
        // scripted out and recreated with its literal name, so the shape check keeps such a constraint
        // normalized across that boundary (see AutoGeneratedNameResilienceTests). The cost is that the
        // rare explicit name deliberately shaped like a system name is also collapsed, as here.
        var db1Name = await CreateTestDatabaseAsync("SysName1");
        var db2Name = await CreateTestDatabaseAsync("SysName2");

        await ExecuteSqlAsync(db1Name, "CREATE TABLE T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY, Age INT NOT NULL, CONSTRAINT [CK__T__AAAAAAAA] CHECK (Age > 0))");
        await ExecuteSqlAsync(db2Name, "CREATE TABLE T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY, Age INT NOT NULL, CONSTRAINT [CK__T__BBBBBBBB] CHECK (Age > 0))");

        var normalize = new SchemaHashOptions { Indexes = IndexNormalization.NormalizeAutoGeneratedNames, Constraints = ConstraintNormalization.NormalizeAutoGeneratedNames };
        (await ExtractAndHashAsync(db1Name, normalize)).ShouldBe(await ExtractAndHashAsync(db2Name, normalize), "A system-shaped constraint name is normalized regardless of is_system_named, so two such names compare equal");

        var ck = (await ExtractSchemaAsync(db1Name)).Tables.Single(t => t.Name == "T").CheckConstraints.Single();
        ck.IsSystemNamed.ShouldBeFalse("Extraction still reports is_system_named = false for an explicitly-named constraint");
    }

    [TestMethod]
    public void Default_IsAliasForV2_AndPresetsReturnFreshInstances()
    {
        var defaults = SchemaHashOptions.Default;
        var v2 = SchemaHashOptions.V2;

        defaults.IgnoreSysDiagramObjects.ShouldBe(v2.IgnoreSysDiagramObjects);
        defaults.Tables.ShouldBe(v2.Tables);
        defaults.Columns.ShouldBe(v2.Columns);
        defaults.Indexes.ShouldBe(v2.Indexes);
        defaults.Constraints.ShouldBe(v2.Constraints);
        defaults.Modules.ShouldBe(v2.Modules);
        defaults.SchemaFilter.ShouldBe(v2.SchemaFilter);
        defaults.ObjectNamesToIgnore.ShouldBe(v2.ObjectNamesToIgnore);

        // Mutating one preset instance must not affect subsequent accesses
        var first = SchemaHashOptions.V2;
        first.Indexes = IndexNormalization.IgnoreSortOrder;
        SchemaHashOptions.V2.Indexes.ShouldBe(IndexNormalization.Strict, "Preset properties must return a fresh instance on every access");
    }

    [TestMethod]
    public async Task IndexSortOrder_SameMetadata_ComputeHashRespectsOption()
    {
        // Direction must be captured in SchemaMetadata so the same extracted schema can be
        // hashed with sort order respected or ignored.
        var dbName = await CreateTestDatabaseAsync("SortOrderMeta");

        await ExecuteSqlAsync(dbName, @"
            CREATE TABLE Assets (
                Id INT NOT NULL CONSTRAINT PK_Assets PRIMARY KEY,
                Created DATETIME2 NOT NULL
            )");
        await ExecuteSqlAsync(dbName, "CREATE INDEX IX_Assets_Created ON Assets(Created DESC)");

        var schema = await ExtractSchemaAsync(dbName);

        var index = schema.Tables.Single(t => t.Name == "Assets").Indexes.Single(i => i.Name == "IX_Assets_Created");
        index.KeyColumns.Count.ShouldBe(1, "The index has a single key column");
        index.KeyColumns[0].Name.ShouldBe("Created", "The key column name must be captured");
        index.KeyColumns[0].IsDescendingKey.ShouldBeTrue("A descending key column must be flagged as descending");

        var hashWithDirection = zachtbeer.SqlSchemaHasher.SqlSchemaHash.ComputeHash(schema, SchemaHashOptions.V2);
        var hashIgnoringDirection = zachtbeer.SqlSchemaHasher.SqlSchemaHash.ComputeHash(schema, SchemaHashOptions.V1);

        hashWithDirection.ShouldNotBe(hashIgnoringDirection, "The same metadata must hash differently under V2 (direction compared) and V1 (direction ignored) when a DESC index exists");
    }
}
