using Dapper;
using Microsoft.Data.SqlClient;
using zachtbeer.SqlSchemaHasher;
using Shouldly;

namespace SqlSchemaHash.IntegrationTests;

/// <summary>
/// Tests for the second round of catalog-fidelity hardening: temporal tables, authoritative
/// is_system_named, is_unique_constraint, constraint NOT FOR REPLICATION, typed-XML parameters, and
/// procedure SET-state (ANSI_NULLS / QUOTED_IDENTIFIER).
/// </summary>
[TestClass]
public class RobustnessGapTests : IntegrationTestBase
{
    #region Temporal tables

    [TestMethod]
    public async Task TemporalTable_VsPlain_ChangesHash_AndTypeIsExtracted()
    {
        var db1Name = await CreateTestDatabaseAsync("Temporal1");
        var db2Name = await CreateTestDatabaseAsync("Plain2");

        await ExecuteSqlAsync(db1Name, @"
            CREATE TABLE T (
                Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY,
                ValidFrom DATETIME2 GENERATED ALWAYS AS ROW START NOT NULL,
                ValidTo DATETIME2 GENERATED ALWAYS AS ROW END NOT NULL,
                PERIOD FOR SYSTEM_TIME (ValidFrom, ValidTo)
            ) WITH (SYSTEM_VERSIONING = ON)");
        await ExecuteSqlAsync(db2Name, @"
            CREATE TABLE T (
                Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY,
                ValidFrom DATETIME2 NOT NULL,
                ValidTo DATETIME2 NOT NULL
            )");

        (await ExtractAndHashAsync(db1Name)).ShouldNotBe(await ExtractAndHashAsync(db2Name), "A system-versioned temporal table must not collide with an otherwise-identical plain table");

        var t = (await ExtractSchemaAsync(db1Name)).Tables.Single(x => x.Name == "T");
        t.TemporalType.ShouldBe("SYSTEM_VERSIONED_TEMPORAL_TABLE", "A temporal table's type must be captured");
        t.Columns.Single(c => c.Name == "ValidFrom").GeneratedAlwaysType.ShouldBe("AS_ROW_START", "A period column's generated-always kind must be captured");
    }

    #endregion

    #region Auto-generated constraint names (is_system_named OR generated shape)

    [TestMethod]
    public async Task ConstraintName_ThatLooksSystemGenerated_IsNormalized_EvenWhenExplicitlyNamed()
    {
        // NormalizeAutoGeneratedNames treats a name as auto-generated when the catalog is_system_named
        // flag is set OR the name matches the generated shape (PK__/CK__ ... __<hex>). This is a
        // deliberate trade for deploy-resilience — the flag flips to 0 when a system-named constraint is
        // scripted out and recreated with its literal name, so the shape check keeps such a constraint
        // normalized across that boundary (see AutoGeneratedNameResilienceTests). The cost is that the
        // rare explicit name deliberately shaped like a system name is also collapsed, as here.
        var db1Name = await CreateTestDatabaseAsync("SysName1");
        var db2Name = await CreateTestDatabaseAsync("SysName2");

        await ExecuteSqlAsync(db1Name, "CREATE TABLE T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY, Age INT NOT NULL, CONSTRAINT [CK__T__AAAAAAAA] CHECK (Age > 0))");
        await ExecuteSqlAsync(db2Name, "CREATE TABLE T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY, Age INT NOT NULL, CONSTRAINT [CK__T__BBBBBBBB] CHECK (Age > 0))");

        var normalize = new SchemaHashOptions { Indexes = IndexNormalization.NormalizeAutoGeneratedNames, Constraints = ConstraintNormalization.NormalizeAutoGeneratedNames };
        (await ExtractAndHashAsync(db1Name, normalize)).ShouldBe(await ExtractAndHashAsync(db2Name, normalize), "A system-shaped constraint name is normalized regardless of is_system_named, so two such names compare equal");

        var ck = (await ExtractSchemaAsync(db1Name)).Tables.Single(t => t.Name == "T").CheckConstraints.Single();
        ck.IsSystemNamed.ShouldBeFalse("Extraction still reports is_system_named = false for an explicitly-named constraint");
    }

    [TestMethod]
    public async Task SystemNamedConstraint_IsFlaggedAsSystemNamed()
    {
        var dbName = await CreateTestDatabaseAsync("SysNameTrue");

        // An inline PRIMARY KEY with no CONSTRAINT name gets a system-generated name.
        await ExecuteSqlAsync(dbName, "CREATE TABLE T (Id INT NOT NULL PRIMARY KEY)");

        var pk = (await ExtractSchemaAsync(dbName)).Tables.Single(t => t.Name == "T").KeyConstraints.Single(c => c.Type == "PRIMARY KEY");
        pk.IsSystemNamed.ShouldBeTrue("A system-generated PK name must report is_system_named = true");
    }

    #endregion

    #region is_unique_constraint

    [TestMethod]
    public async Task UniqueConstraint_VsUniqueIndex_ChangesHash_AndIsExtracted()
    {
        var db1Name = await CreateTestDatabaseAsync("UqCon1");
        var db2Name = await CreateTestDatabaseAsync("UqIdx2");

        await ExecuteSqlAsync(db1Name, "CREATE TABLE T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY, A INT NOT NULL CONSTRAINT UQ_T UNIQUE)");
        await ExecuteSqlAsync(db2Name, "CREATE TABLE T (Id INT NOT NULL CONSTRAINT PK_T PRIMARY KEY, A INT NOT NULL)");
        await ExecuteSqlAsync(db2Name, "CREATE UNIQUE INDEX UQ_T ON T(A)");

        (await ExtractAndHashAsync(db1Name)).ShouldNotBe(await ExtractAndHashAsync(db2Name), "A UNIQUE constraint is distinct from a plain unique index and must change the hash");

        var idx = (await ExtractSchemaAsync(db1Name)).Tables.Single(t => t.Name == "T").Indexes.Single(i => i.Name == "UQ_T");
        idx.IsUniqueConstraint.ShouldBeTrue("A unique-constraint-backed index must report is_unique_constraint = true");
    }

    #endregion

    #region Constraint NOT FOR REPLICATION

    [TestMethod]
    public async Task ForeignKey_NotForReplication_ChangesHash()
    {
        var db1Name = await CreateTestDatabaseAsync("FkNfr1");
        var db2Name = await CreateTestDatabaseAsync("FkNfr2");

        const string baseSql = @"
            CREATE TABLE Parent (Id INT NOT NULL CONSTRAINT PK_P PRIMARY KEY);
            CREATE TABLE Child (Id INT NOT NULL CONSTRAINT PK_C PRIMARY KEY, PId INT NULL);";
        await ExecuteSqlAsync(db1Name, baseSql);
        await ExecuteSqlAsync(db2Name, baseSql);

        await ExecuteSqlAsync(db1Name, "ALTER TABLE Child ADD CONSTRAINT FK_C FOREIGN KEY (PId) REFERENCES Parent(Id) NOT FOR REPLICATION");
        await ExecuteSqlAsync(db2Name, "ALTER TABLE Child ADD CONSTRAINT FK_C FOREIGN KEY (PId) REFERENCES Parent(Id)");

        (await ExtractAndHashAsync(db1Name)).ShouldNotBe(await ExtractAndHashAsync(db2Name), "A NOT FOR REPLICATION foreign key differs behaviorally and must change the hash");
    }

    #endregion

    #region Typed-XML parameters

    [TestMethod]
    public async Task Parameter_TypedXml_ChangesHash_AndCollectionIsExtracted()
    {
        var db1Name = await CreateTestDatabaseAsync("XmlParam1");
        var db2Name = await CreateTestDatabaseAsync("XmlParam2");

        const string collection = @"
            CREATE XML SCHEMA COLLECTION dbo.DocSchema AS
            '<xsd:schema xmlns:xsd=""http://www.w3.org/2001/XMLSchema""><xsd:element name=""root"" type=""xsd:string""/></xsd:schema>';";
        await ExecuteSqlAsync(db1Name, collection);
        await ExecuteSqlAsync(db1Name, "CREATE PROCEDURE P @doc XML(dbo.DocSchema) AS BEGIN SELECT 1 END");
        await ExecuteSqlAsync(db2Name, "CREATE PROCEDURE P @doc XML AS BEGIN SELECT 1 END");

        (await ExtractAndHashAsync(db1Name)).ShouldNotBe(await ExtractAndHashAsync(db2Name), "A typed-XML parameter must not collide with an untyped-XML parameter");

        var p = (await ExtractSchemaAsync(db1Name)).StoredProcedures.Single(x => x.Name == "P").Parameters.Single(x => x.Name == "doc");
        p.XmlSchemaCollectionName.ShouldBe("dbo.DocSchema", "A typed-XML parameter must carry its schema-qualified collection name");
    }

    #endregion

    #region Procedure SET states

    [TestMethod]
    public async Task Procedure_QuotedIdentifierSetting_ChangesHash_AndIsExtracted()
    {
        // QUOTED_IDENTIFIER is baked in at CREATE time and is NOT part of the module text, so two procs
        // with byte-identical bodies but different SET state must still hash differently.
        var db1Name = await CreateTestDatabaseAsync("Qi1");
        var db2Name = await CreateTestDatabaseAsync("Qi2");

        const string procSql = "CREATE PROCEDURE P AS BEGIN SELECT 1 END";
        await ExecuteSqlAsync(db1Name, procSql); // QUOTED_IDENTIFIER ON (client default)

        // Flip the session setting and create the proc on the SAME connection so the OFF state sticks.
        await using (var connection = new SqlConnection(GetConnectionString(db2Name)))
        {
            await connection.OpenAsync();
            await connection.ExecuteAsync("SET QUOTED_IDENTIFIER OFF");
            await connection.ExecuteAsync(procSql);
        }

        (await ExtractAndHashAsync(db1Name)).ShouldNotBe(await ExtractAndHashAsync(db2Name), "QUOTED_IDENTIFIER baked at create time must change the hash even with identical body text");

        var proc = (await ExtractSchemaAsync(db2Name)).StoredProcedures.Single(p => p.Name == "P");
        proc.UsesQuotedIdentifier.ShouldBeFalse("A proc created under SET QUOTED_IDENTIFIER OFF must be reported as such");
    }

    #endregion
}
