using SqlSchemaHash.IntegrationTests.TestHelpers;
using zachtbeer.SqlSchemaHasher;
using Shouldly;

namespace SqlSchemaHash.IntegrationTests;

[TestClass]
public class SchemaHashingTests : IntegrationTestBase
{
    [TestMethod]
    public async Task IdenticalSchemas_ProduceSameHash()
    {
        // Arrange - Create two databases with identical schemas
        var db1Name = await CreateTestDatabaseAsync("HashTest_Identical1");
        var db2Name = await CreateTestDatabaseAsync("HashTest_Identical2");

        await DatabaseTestHelpers.CreateEmployeesSchemaAsync(db1Name);
        await DatabaseTestHelpers.CreateEmployeesSchemaAsync(db2Name);

        // Act
        var hash1 = await ExtractAndHashAsync(db1Name);
        var hash2 = await ExtractAndHashAsync(db2Name);

        // Assert
        hash1.ShouldBe(hash2, "Identical schemas should produce the same hash");
        hash1.Length.ShouldBe(64, "SHA256 hash should be 64 hex characters");
    }

    [TestMethod]
    public async Task DifferentSchemas_ProduceDifferentHashes()
    {
        // Arrange - Create two databases with different schemas
        var db1Name = await CreateTestDatabaseAsync("HashTest_Different1");
        var db2Name = await CreateTestDatabaseAsync("HashTest_Different2");

        await DatabaseTestHelpers.CreateEmployeesSchemaAsync(db1Name);
        await CreateDifferentSchema(db2Name);

        // Act
        var hash1 = await ExtractAndHashAsync(db1Name);
        var hash2 = await ExtractAndHashAsync(db2Name);

        // Assert
        hash1.ShouldNotBe(hash2, "Different schemas should produce different hashes");
    }

    [TestMethod]
    public async Task HashWithNormalization_IgnoresAutoGeneratedIndexNames()
    {
        // Arrange - Create two databases where indexes have different auto-generated suffixes
        var db1Name = await CreateTestDatabaseAsync("HashTest_IndexNorm1");
        var db2Name = await CreateTestDatabaseAsync("HashTest_IndexNorm2");

        await CreateSchemaWithNamedIndex(db1Name, "IX_Employees_Name_ABC12345DEF67890");
        await CreateSchemaWithNamedIndex(db2Name, "IX_Employees_Name_123456789ABCDEF0");

        // Act - With normalization enabled
        var normalizedOptions = new SchemaHashOptions { Indexes = IndexNormalization.NormalizeAutoGeneratedNames, Constraints = ConstraintNormalization.NormalizeAutoGeneratedNames };
        var exactOptions = new SchemaHashOptions();

        var normalizedHash1 = await ExtractAndHashAsync(db1Name, normalizedOptions);
        var normalizedHash2 = await ExtractAndHashAsync(db2Name, normalizedOptions);

        var exactHash1 = await ExtractAndHashAsync(db1Name, exactOptions);
        var exactHash2 = await ExtractAndHashAsync(db2Name, exactOptions);

        // Assert
        normalizedHash1.ShouldBe(normalizedHash2, "Normalized hashes should match when only index name suffixes differ");
        exactHash1.ShouldNotBe(exactHash2, "Exact hashes should differ when index names are different");
    }

    [TestMethod]
    public async Task SchemaExtractor_ExtractsAllObjectTypes()
    {
        // Arrange
        var dbName = await CreateTestDatabaseAsync("HashTest_AllObjects");
        await DatabaseTestHelpers.CreateComprehensiveSchemaAsync(dbName);

        // Act
        var schema = await ExtractSchemaAsync(dbName);

        // Assert - tables
        schema.Tables.Count.ShouldBeGreaterThan(0, "Should extract tables");
        schema.Tables.Any(t => t.Columns.Count > 0).ShouldBeTrue("Tables should have columns");
        schema.Tables.Any(t => t.Indexes.Count > 0).ShouldBeTrue("Tables should have indexes");

        // Assert - stored procedures with definition hash
        schema.StoredProcedures.Count.ShouldBeGreaterThan(0, "Should extract stored procedures");
        var proc = schema.StoredProcedures.First();
        proc.DefinitionHash.ShouldNotBeNullOrEmpty("DefinitionHash should be populated");
        proc.DefinitionHash.Length.ShouldBe(64, "SHA256 hash should be 64 hex chars");

        // Assert - user-defined table types
        schema.UserDefinedTableTypes.Count.ShouldBeGreaterThan(0, "Should extract user-defined table types");
        var udt = schema.UserDefinedTableTypes.First();
        udt.Columns.Count.ShouldBeGreaterThan(0, "UDT should have columns");
    }

    #region Edge Case Tests

    [TestMethod]
    public async Task SchemaExtractor_HandlesEmptyDatabase()
    {
        // Arrange - Create two empty databases with no user objects
        var db1Name = await CreateTestDatabaseAsync("HashTest_Empty1");
        var db2Name = await CreateTestDatabaseAsync("HashTest_Empty2");

        // Act
        var schema = await ExtractSchemaAsync(db1Name);
        var hash1 = await ExtractAndHashAsync(db1Name);
        var hash2 = await ExtractAndHashAsync(db2Name);

        // Assert - Should not throw and should produce valid output
        schema.ShouldNotBeNull();
        schema.Tables.Count.ShouldBe(0, "Empty database should have no tables");
        schema.StoredProcedures.Count.ShouldBe(0, "Empty database should have no stored procedures");
        hash1.ShouldNotBeNullOrEmpty("Should produce a valid hash even for empty database");
        hash1.Length.ShouldBe(64, "SHA256 hash should be 64 hex characters");

        // Two empty databases should have the same hash (absorbed from ProducesConsistentHashForEmptyDatabases)
        hash1.ShouldBe(hash2, "Two empty databases should have identical hashes");
    }

    [TestMethod]
    public async Task SchemaExtractor_FiltersSystemObjects()
    {
        // Arrange - Create database with sysdiagrams (should be filtered)
        var dbName = await CreateTestDatabaseAsync("HashTest_SysObjects");

        await ExecuteSqlAsync(dbName, @"
            CREATE TABLE sysdiagrams (
                name sysname NOT NULL,
                principal_id int NOT NULL,
                diagram_id int IDENTITY(1,1) PRIMARY KEY,
                version int,
                definition varbinary(max)
            )");

        // Act
        var schema = await ExtractSchemaAsync(dbName);

        // Assert - sysdiagrams should be filtered out
        schema.Tables.Any(t => t.Name.Equals("sysdiagrams", StringComparison.OrdinalIgnoreCase))
            .ShouldBeFalse("sysdiagrams table should be filtered out of schema extraction");
    }

    [TestMethod]
    public async Task SchemaExtractor_ExtractsConstraints()
    {
        // Arrange
        var dbName = await CreateTestDatabaseAsync("HashTest_Constraints");

        await ExecuteSqlAsync(dbName, @"
            CREATE TABLE Departments (
                DepartmentId INT IDENTITY(1,1) PRIMARY KEY,
                Name NVARCHAR(50) NOT NULL UNIQUE
            )");

        await ExecuteSqlAsync(dbName, @"
            CREATE TABLE Employees (
                EmployeeId INT IDENTITY(1,1) PRIMARY KEY,
                DepartmentId INT NOT NULL,
                Name NVARCHAR(100) NOT NULL,
                Salary DECIMAL(10,2) NOT NULL,
                CONSTRAINT CK_Employees_Salary CHECK (Salary >= 0),
                CONSTRAINT FK_Employees_Departments FOREIGN KEY (DepartmentId) REFERENCES Departments(DepartmentId)
            )");

        // Act
        var schema = await ExtractSchemaAsync(dbName);

        // Assert
        var employeesTable = schema.Tables.FirstOrDefault(t => t.Name == "Employees");
        employeesTable.ShouldNotBeNull();

        var totalConstraints = employeesTable.KeyConstraints.Count + employeesTable.ForeignKeys.Count + employeesTable.CheckConstraints.Count + employeesTable.DefaultConstraints.Count;
        totalConstraints.ShouldBeGreaterThan(0, "Should extract constraints");
        employeesTable.ForeignKeys.Count.ShouldBeGreaterThan(0, "Should have foreign key constraint");
    }

    [TestMethod]
    public async Task SchemaExtractor_HandlesDatabaseWithOnlyStoredProcedures()
    {
        // Arrange
        var dbName = await CreateTestDatabaseAsync("HashTest_OnlyProcs");

        await ExecuteSqlAsync(dbName, @"
            CREATE PROCEDURE GetServerVersion
            AS
            BEGIN
                SELECT @@VERSION
            END");

        await ExecuteSqlAsync(dbName, @"
            CREATE PROCEDURE GetServerName
            AS
            BEGIN
                SELECT @@SERVERNAME
            END");

        // Act
        var schema = await ExtractSchemaAsync(dbName);
        var hash = await ExtractAndHashAsync(dbName);

        // Assert
        schema.Tables.Count.ShouldBe(0, "Should have no tables");
        schema.StoredProcedures.Count.ShouldBe(2, "Should have 2 stored procedures");
        hash.ShouldNotBeNullOrEmpty("Should produce valid hash for database with only stored procedures");
    }

    #endregion

    #region Stored Procedure Definition Hash Tests

    [TestMethod]
    public async Task StoredProcDefinition_DifferentBodies_ProduceDifferentHashes()
    {
        // Arrange - Two procedures with same name/params but different body
        var db1Name = await CreateTestDatabaseAsync("ProcHash_Body1");
        var db2Name = await CreateTestDatabaseAsync("ProcHash_Body2");

        await ExecuteSqlAsync(db1Name, @"
            CREATE PROCEDURE GetValue @id INT
            AS BEGIN SELECT @id * 2 END");

        await ExecuteSqlAsync(db2Name, @"
            CREATE PROCEDURE GetValue @id INT
            AS BEGIN SELECT @id * 3 END");

        // Act
        var hash1 = await ExtractAndHashAsync(db1Name);
        var hash2 = await ExtractAndHashAsync(db2Name);

        // Assert
        hash1.ShouldNotBe(hash2, "Procs with different bodies must produce different hashes");
    }

    [TestMethod]
    public async Task StoredProcDefinition_IdenticalBodies_ProduceSameHash()
    {
        // Arrange
        var db1Name = await CreateTestDatabaseAsync("ProcHash_Same1");
        var db2Name = await CreateTestDatabaseAsync("ProcHash_Same2");

        var procDef = @"
            CREATE PROCEDURE GetProjectById @projectId INT
            AS
            BEGIN
                SET NOCOUNT ON;
                SELECT ProjectId, Name FROM Projects WHERE ProjectId = @projectId
            END";

        await ExecuteSqlAsync(db1Name, "CREATE TABLE Projects (ProjectId INT, Name NVARCHAR(100))");
        await ExecuteSqlAsync(db2Name, "CREATE TABLE Projects (ProjectId INT, Name NVARCHAR(100))");
        await ExecuteSqlAsync(db1Name, procDef);
        await ExecuteSqlAsync(db2Name, procDef);

        // Act
        var hash1 = await ExtractAndHashAsync(db1Name);
        var hash2 = await ExtractAndHashAsync(db2Name);

        // Assert
        hash1.ShouldBe(hash2, "Identical procedure definitions must produce same hash");
    }

    [TestMethod]
    public async Task StoredProcDefinition_ModifiedBody_ChangesHash()
    {
        // Arrange
        var dbName = await CreateTestDatabaseAsync("ProcHash_Alter");

        await ExecuteSqlAsync(dbName, @"
            CREATE PROCEDURE CalculateTotal @qty INT, @price DECIMAL(10,2)
            AS BEGIN SELECT @qty * @price END");

        // Act - Get hash before ALTER
        var hashBefore = await ExtractAndHashAsync(dbName);

        // ALTER the procedure body
        await ExecuteSqlAsync(dbName, @"
            ALTER PROCEDURE CalculateTotal @qty INT, @price DECIMAL(10,2)
            AS BEGIN SELECT @qty * @price * 1.1 END");

        var hashAfter = await ExtractAndHashAsync(dbName);

        // Assert
        hashBefore.ShouldNotBe(hashAfter, "ALTER PROCEDURE should change the hash");
    }

    [TestMethod]
    public async Task StoredProcDefinition_WhitespaceChanges_AffectHash()
    {
        // Arrange - Two procedures with same logic but different whitespace/comments
        var db1Name = await CreateTestDatabaseAsync("ProcHash_WS1");
        var db2Name = await CreateTestDatabaseAsync("ProcHash_WS2");

        await ExecuteSqlAsync(db1Name, @"CREATE PROCEDURE GetData AS BEGIN SELECT 1 END");

        await ExecuteSqlAsync(db2Name, @"
            CREATE PROCEDURE GetData
            AS
            BEGIN
                -- This is a comment
                SELECT 1
            END");

        // Act
        var hash1 = await ExtractAndHashAsync(db1Name);
        var hash2 = await ExtractAndHashAsync(db2Name);

        // Assert
        hash1.ShouldNotBe(hash2, "Whitespace and comment changes affect the definition hash");
    }

    [TestMethod]
    public async Task StoredProcDefinition_InDifferentSchemas_ProduceDifferentHashes()
    {
        // Arrange - Same proc name and body, but in different schemas
        var db1Name = await CreateTestDatabaseAsync("ProcHash_Schema1");
        var db2Name = await CreateTestDatabaseAsync("ProcHash_Schema2");

        await ExecuteSqlAsync(db1Name, "CREATE SCHEMA sales");
        await ExecuteSqlAsync(db2Name, "CREATE SCHEMA reporting");

        await ExecuteSqlAsync(db1Name, @"
            CREATE PROCEDURE sales.GetData AS BEGIN SELECT 1 END");
        await ExecuteSqlAsync(db2Name, @"
            CREATE PROCEDURE reporting.GetData AS BEGIN SELECT 1 END");

        // Act
        var hash1 = await ExtractAndHashAsync(db1Name);
        var hash2 = await ExtractAndHashAsync(db2Name);

        // Assert
        hash1.ShouldNotBe(hash2, "Procs in different schemas must produce different hashes");
    }

    #endregion

    #region Public API Tests

    [TestMethod]
    public async Task PublicApi_GetHashAsync_ReturnsVersionedEnvelope()
    {
        // Arrange
        var dbName = await CreateTestDatabaseAsync("PublicApi_Base64");
        await DatabaseTestHelpers.CreateEmployeesSchemaAsync(dbName);

        var connectionString = GetConnectionString(dbName);

        // Act
        var hash1 = await zachtbeer.SqlSchemaHasher.SqlSchemaHash.GetHashAsync(connectionString);
        var hash2 = await zachtbeer.SqlSchemaHasher.SqlSchemaHash.GetHashAsync(connectionString);

        // Assert - "<version>:<base64hash>" envelope
        System.Text.RegularExpressions.Regex.IsMatch(hash1, @"^\d+:").ShouldBeTrue($"Expected a versioned envelope, got '{hash1}'");
        SchemaHashResult.TryParse(hash1, out var parsed).ShouldBeTrue("The envelope should parse");
        parsed.Version.ShouldBe(2, "Default hash-format version is the assembly major (2.x)");
        parsed.Hash.Length.ShouldBe(44, "Base64-encoded SHA256 (32 bytes) is 44 characters with padding");
        hash1.ShouldBe(hash2, "Public API should return consistent results");
    }

    [TestMethod]
    public async Task PublicApi_GetHashAsync_WithOptions_AppliesOptions()
    {
        // Arrange
        var dbName = await CreateTestDatabaseAsync("PublicApi_Options");
        await DatabaseTestHelpers.CreateEmployeesSchemaAsync(dbName);

        var connectionString = GetConnectionString(dbName);

        // Act - default includes stored procedure text
        var hashDefault = await zachtbeer.SqlSchemaHasher.SqlSchemaHash.GetHashAsync(connectionString);
        var hashNoProc = await zachtbeer.SqlSchemaHasher.SqlSchemaHash.GetHashAsync(connectionString, new SchemaHashOptions { Modules = ModuleNormalization.IgnoreBodyText });

        // Assert - different options should produce different hashes
        hashDefault.ShouldNotBe(hashNoProc, "IncludeStoredProcedureText=false should produce a different hash");
    }

    #endregion

    #region Schema Filter Tests

    [TestMethod]
    public async Task SchemaFilter_IncludesOnlyMatchingSchema()
    {
        // Arrange
        var dbName = await CreateTestDatabaseAsync("Filter_Schema");

        await ExecuteSqlAsync(dbName, "CREATE SCHEMA sales");
        await ExecuteSqlAsync(dbName, "CREATE TABLE dbo.DboTable (Id INT PRIMARY KEY)");
        await ExecuteSqlAsync(dbName, "CREATE TABLE sales.SalesTable (Id INT PRIMARY KEY)");
        await ExecuteSqlAsync(dbName, @"CREATE PROCEDURE dbo.DboProc AS BEGIN SELECT 1 END");
        await ExecuteSqlAsync(dbName, @"CREATE PROCEDURE sales.SalesProc AS BEGIN SELECT 1 END");

        // Act
        var salesOptions = new SchemaHashOptions { SchemaFilter = "sales" };
        var filteredSchema = await ExtractSchemaAsync(dbName, salesOptions);
        var filteredHash = await ExtractAndHashAsync(dbName, salesOptions);
        var unfilteredHash = await ExtractAndHashAsync(dbName);

        // Assert - only sales objects
        filteredSchema.Tables.ShouldAllBe(t => t.SchemaName == "sales", "Should only contain sales tables");
        filteredSchema.Tables.Count.ShouldBe(1);
        filteredSchema.StoredProcedures.ShouldAllBe(p => p.SchemaName == "sales", "Should only contain sales procs");
        filteredSchema.StoredProcedures.Count.ShouldBe(1);

        // Filtered hash should differ from unfiltered
        filteredHash.ShouldNotBe(unfilteredHash, "Filtered hash should differ from unfiltered");
    }

    #endregion

    #region Normalization Tests

    [TestMethod]
    public async Task NormalizeClusteringType_MatchesClusteredAndNonclustered()
    {
        // Arrange - Two DBs: one with clustered index, one with nonclustered on same column
        var db1Name = await CreateTestDatabaseAsync("Cluster_Clustered");
        var db2Name = await CreateTestDatabaseAsync("Cluster_NonClustered");

        // DB1: heap table with a clustered index on Name
        await ExecuteSqlAsync(db1Name, @"
            CREATE TABLE Assets (
                Id INT NOT NULL,
                Name NVARCHAR(100) NOT NULL
            )");
        await ExecuteSqlAsync(db1Name, "CREATE CLUSTERED INDEX IX_Assets_Name ON Assets(Name)");

        // DB2: heap table with a nonclustered index on Name
        await ExecuteSqlAsync(db2Name, @"
            CREATE TABLE Assets (
                Id INT NOT NULL,
                Name NVARCHAR(100) NOT NULL
            )");
        await ExecuteSqlAsync(db2Name, "CREATE NONCLUSTERED INDEX IX_Assets_Name ON Assets(Name)");

        // Act
        var exactOptions = new SchemaHashOptions();
        var normalizedOptions = new SchemaHashOptions { Indexes = IndexNormalization.NormalizeClustering };

        var exactHash1 = await ExtractAndHashAsync(db1Name, exactOptions);
        var exactHash2 = await ExtractAndHashAsync(db2Name, exactOptions);

        var normHash1 = await ExtractAndHashAsync(db1Name, normalizedOptions);
        var normHash2 = await ExtractAndHashAsync(db2Name, normalizedOptions);

        // Assert
        exactHash1.ShouldNotBe(exactHash2, "Without normalization, clustered vs nonclustered should differ");
        normHash1.ShouldBe(normHash2, "With normalization, clustered vs nonclustered should match");
    }

    [TestMethod]
    public async Task AutoGeneratedIndexNames_WithoutNormalization_ProduceDifferentHashes()
    {
        // Arrange - Two databases with inline PKs that get auto-generated index names
        var db1Name = await CreateTestDatabaseAsync("AutoIdx_Norm1");
        var db2Name = await CreateTestDatabaseAsync("AutoIdx_Norm2");

        // Inline PRIMARY KEY causes SQL Server to generate PK index names with random hex suffixes
        await ExecuteSqlAsync(db1Name, @"
            CREATE TABLE Products (
                ProductId INT IDENTITY(1,1) PRIMARY KEY,
                Name NVARCHAR(100) NOT NULL
            )");
        await ExecuteSqlAsync(db2Name, @"
            CREATE TABLE Products (
                ProductId INT IDENTITY(1,1) PRIMARY KEY,
                Name NVARCHAR(100) NOT NULL
            )");

        // Act
        var defaultOptions = new SchemaHashOptions { Modules = ModuleNormalization.IgnoreBodyText };
        var normalizedOptions = new SchemaHashOptions { Indexes = IndexNormalization.NormalizeAutoGeneratedNames, Constraints = ConstraintNormalization.NormalizeAutoGeneratedNames, Modules = ModuleNormalization.IgnoreBodyText };

        var defaultHash1 = await ExtractAndHashAsync(db1Name, defaultOptions);
        var defaultHash2 = await ExtractAndHashAsync(db2Name, defaultOptions);

        var normalizedHash1 = await ExtractAndHashAsync(db1Name, normalizedOptions);
        var normalizedHash2 = await ExtractAndHashAsync(db2Name, normalizedOptions);

        // Assert - auto-generated PK names differ across databases, so hashes differ without normalization
        defaultHash1.ShouldNotBe(defaultHash2, "Auto-generated PK index names should cause different hashes without normalization");
        // With normalization, the GUID suffixes are stripped and hashes should match
        normalizedHash1.ShouldBe(normalizedHash2, "With normalization enabled, auto-generated PK index names should be ignored");
    }

    [TestMethod]
    public async Task IncludeStoredProcedureText_WhenFalse_IgnoresBodyChanges()
    {
        // Arrange - Two DBs with same proc name/params but different body
        var db1Name = await CreateTestDatabaseAsync("ProcText_Body1");
        var db2Name = await CreateTestDatabaseAsync("ProcText_Body2");

        await ExecuteSqlAsync(db1Name, @"
            CREATE PROCEDURE CalcValue @x INT
            AS BEGIN SELECT @x * 2 END");

        await ExecuteSqlAsync(db2Name, @"
            CREATE PROCEDURE CalcValue @x INT
            AS BEGIN SELECT @x * 99 END");

        // Act
        var withText = new SchemaHashOptions();
        var withoutText = new SchemaHashOptions { Modules = ModuleNormalization.IgnoreBodyText };

        var hashWith1 = await ExtractAndHashAsync(db1Name, withText);
        var hashWith2 = await ExtractAndHashAsync(db2Name, withText);

        var hashWithout1 = await ExtractAndHashAsync(db1Name, withoutText);
        var hashWithout2 = await ExtractAndHashAsync(db2Name, withoutText);

        // Assert
        hashWith1.ShouldNotBe(hashWith2, "With IncludeStoredProcedureText=true, different bodies should differ");
        hashWithout1.ShouldBe(hashWithout2, "With IncludeStoredProcedureText=false, different bodies should match");
    }

    #endregion

    #region Private Helper Methods

    private async Task CreateDifferentSchema(string dbName)
    {
        await ExecuteSqlAsync(dbName, @"
            CREATE TABLE Projects (
                ProjectId INT IDENTITY(1,1) PRIMARY KEY,
                Code NVARCHAR(255) NOT NULL,
                Name NVARCHAR(50),
                Description NVARCHAR(50)
            )");

        await ExecuteSqlAsync(dbName, @"
            CREATE INDEX IX_Projects_Code ON Projects(Code)");
    }

    private async Task CreateSchemaWithNamedIndex(string dbName, string indexName)
    {
        await ExecuteSqlAsync(dbName, @"
            CREATE TABLE Employees (
                EmployeeId INT IDENTITY(1,1) PRIMARY KEY,
                Name NVARCHAR(100) NOT NULL
            )");

        await ExecuteSqlAsync(dbName, $@"
            CREATE INDEX [{indexName}] ON Employees(Name)");
    }

    #endregion
}
