namespace zachtbeer.SqlSchemaHasher;

/// <summary>
/// Configuration options for schema hash calculation.
/// A bare <c>new SchemaHashOptions()</c> is the neutral baseline: everything compared exactly, nothing excluded.
/// Use the static presets (<see cref="V1"/>, <see cref="V2"/>, <see cref="Structural"/>) for common configurations.
/// </summary>
public sealed class SchemaHashOptions
{
	/// <summary>
	/// Object names belonging to SSMS database diagrams (sysdiagrams table and related helper procs),
	/// excluded from extraction when <see cref="IgnoreSysDiagramObjects"/> is set.
	/// </summary>
	internal static readonly IReadOnlySet<string> SysDiagramObjectNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
	{
		"sysdiagrams",
		"fn_diagramobjects",
		"sp_alterdiagram",
		"sp_creatediagram",
		"sp_dropdiagram",
		"sp_helpdiagramdefinition",
		"sp_helpdiagrams",
		"sp_renamediagram"
	};

	/// <summary>
	/// Recommended defaults. Alias for <see cref="V2"/>.
	/// </summary>
	public static SchemaHashOptions Default => V2;

	/// <summary>
	/// Comparison semantics matching v1 of this library: exact index names, exact clustering type,
	/// index key sort order not compared (v1 never captured it), stored procedure text included,
	/// SSMS diagram objects ignored. Note: hashes still differ from package v1.x output because
	/// v2 extraction fidelity fixes apply unconditionally.
	/// </summary>
	public static SchemaHashOptions V1 => new() { IgnoreSysDiagramObjects = true, IgnoreIndexSortOrder = true };

	/// <summary>
	/// Recommended v2 defaults: everything compared exactly (including index key sort order),
	/// SSMS diagram objects ignored.
	/// </summary>
	public static SchemaHashOptions V2 => new() { IgnoreSysDiagramObjects = true };

	/// <summary>
	/// Opinionated structural comparison: answers "is the schema logically the same?" by ignoring
	/// naming and physical layout noise — clustered vs nonclustered, index key sort order, index
	/// names entirely, and SSMS diagram objects. Columns, key column sets, included columns,
	/// uniqueness/primary-key-ness, constraints, identity columns, and stored procedures are still compared.
	/// </summary>
	public static SchemaHashOptions Structural => new() { IgnoreSysDiagramObjects = true, IgnoreIndexNames = true, NormalizeClusteringType = true, IgnoreIndexSortOrder = true, IgnoreConstraintNames = true };

	/// <summary>
	/// Object names to exclude from schema extraction (case-insensitive).
	/// Default: empty (no objects excluded). Composes additively with <see cref="IgnoreSysDiagramObjects"/>.
	/// </summary>
	public IReadOnlySet<string> ObjectNamesToIgnore { get; set; } = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

	/// <summary>
	/// When true, excludes SSMS database diagram objects (sysdiagrams table and related helper procs)
	/// from schema extraction, in addition to any names in <see cref="ObjectNamesToIgnore"/>.
	/// Default: false. Enabled by all presets (<see cref="V1"/>, <see cref="V2"/>, <see cref="Structural"/>).
	/// </summary>
	public bool IgnoreSysDiagramObjects { get; set; } = false;

	/// <summary>
	/// Filter to include only objects from specific schema(s).
	/// When null (default), all schemas are included.
	/// Examples: "dbo", "sales", "reporting"
	/// </summary>
	public string? SchemaFilter { get; set; } = null;

	/// <summary>
	/// When true, index names detected as auto-generated are replaced by a fixed sentinel in the hash,
	/// so two databases whose auto-generated names differ only in their generated suffix compare equal.
	/// Detection covers SQL Server system-generated names (e.g. 'PK__Employee__3214EC07A1B2C3D4')
	/// and GUID-suffixed names (e.g. 'nci_wi_Asset_EF8A0893C0DB8B0FC4AD9EABBE187744').
	/// Explicitly-named indexes still compare exactly. Ignored when <see cref="IgnoreIndexNames"/> is set.
	/// Default: false (exact name comparison).
	/// </summary>
	public bool NormalizeAutoGeneratedIndexNames { get; set; } = false;

	/// <summary>
	/// When true, index names are excluded from the hash entirely — only the index definition
	/// (keys, included columns, uniqueness, type) matters. Takes precedence over
	/// <see cref="NormalizeAutoGeneratedIndexNames"/>.
	/// Default: false. Enabled by <see cref="Structural"/>.
	/// </summary>
	public bool IgnoreIndexNames { get; set; } = false;

	/// <summary>
	/// When true, constraint names (PRIMARY KEY, FOREIGN KEY, UNIQUE, CHECK, DEFAULT) are excluded
	/// from the hash — only the constraint definition (type, keys/expression, enforcement state)
	/// matters. When false (default), renaming a constraint changes the hash, mirroring the exact
	/// index-name comparison of <see cref="IgnoreIndexNames"/>.
	/// Default: false (names compared). Enabled by <see cref="Structural"/>.
	/// </summary>
	public bool IgnoreConstraintNames { get; set; } = false;

	/// <summary>
	/// When true, normalizes clustered/nonclustered index types to a common value.
	/// Useful when index clustering doesn't matter for schema comparison.
	/// Default: false. Enabled by <see cref="Structural"/>.
	/// </summary>
	public bool NormalizeClusteringType { get; set; } = false;

	/// <summary>
	/// When true, index key sort order (ASC/DESC) is excluded from the hash.
	/// Default: false (sort order is compared). Enabled by <see cref="V1"/> (which never captured
	/// sort order) and <see cref="Structural"/>.
	/// </summary>
	public bool IgnoreIndexSortOrder { get; set; } = false;

	/// <summary>
	/// When true, includes stored procedure body text in the hash calculation.
	/// When false, only the procedure name and parameter signatures are hashed.
	/// Default: true (procedure body changes will change the hash).
	/// </summary>
	public bool IncludeStoredProcedureText { get; set; } = true;
}
