namespace zachtbeer.SqlSchemaHasher;

/// <summary>
/// Configuration options for schema hash calculation.
/// </summary>
public sealed class SchemaHashOptions
{
	/// <summary>
	/// Returns a new instance with opinionated defaults: filters out SQL Server diagram objects
	/// (sysdiagrams table and related helper procs).
	/// </summary>
	public static SchemaHashOptions Default => new()
	{
		ObjectNamesToIgnore = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
		{
			"sysdiagrams",
			"fn_diagramobjects",
			"sp_alterdiagram",
			"sp_creatediagram",
			"sp_dropdiagram",
			"sp_helpdiagramdefinition",
			"sp_helpdiagrams",
			"sp_renamediagram"
		}
	};

	/// <summary>
	/// Object names to exclude from schema extraction (case-insensitive).
	/// Default: empty (no objects excluded). Use <see cref="Default"/> for opinionated exclusions.
	/// </summary>
	public IReadOnlySet<string> ObjectNamesToIgnore { get; set; } = new HashSet<string>(StringComparer.OrdinalIgnoreCase);

	/// <summary>
	/// Filter to include only objects from specific schema(s).
	/// When null (default), all schemas are included.
	/// Examples: "dbo", "sales", "reporting"
	/// </summary>
	public string? SchemaFilter { get; set; } = null;

	/// <summary>
	/// When true, normalizes auto-generated index names by stripping GUID suffixes
	/// (e.g., 'nci_wi_Asset_EF8A0893C0DB8B0FC4AD9EABBE187744' -> 'nci_wi_Asset').
	/// Default: false (exact name comparison - goal is to standardize all names eventually).
	/// </summary>
	public bool NormalizeAutoGeneratedIndexNames { get; set; } = false;

	/// <summary>
	/// When true, normalizes clustered/nonclustered index types to a common value.
	/// Useful when index clustering doesn't matter for schema comparison.
	/// Default: false.
	/// </summary>
	public bool NormalizeClusteringType { get; set; } = false;

	/// <summary>
	/// When true, includes stored procedure body text in the hash calculation.
	/// When false, only the procedure name and parameter signatures are hashed.
	/// Default: true (procedure body changes will change the hash).
	/// </summary>
	public bool IncludeStoredProcedureText { get; set; } = true;
}
