namespace zachtbeer.SqlSchemaHasher;

// Domain-grouped normalization flags. Each enum governs one schema area and follows a single
// invariant: Strict == 0 == hash this domain with full fidelity, and every bit only ever *removes*
// a distinction from the hash (loosens the comparison). So a bare set of Strict enums (the default
// on SchemaHashOptions) is the neutral everything-exact baseline, and named combos such as
// Structural are just unions of loosening bits. Because "no bits" reproduces the pre-existing field
// layout with the pre-existing values, the Strict baseline is byte-for-byte hash-compatible with
// earlier output.
//
// The named combos (Strict/Structural) are deliberately defined to match the semantics of the
// existing SchemaHashOptions presets so their hashes are unchanged; whether the newer physical /
// enforcement / collation bits should be folded into a preset is a separate decision (the presets
// round) and is intentionally NOT done here.

/// <summary>
/// Normalization of table-level facets: table column order and identity/temporal metadata.
/// Applies to base tables; the identity bits also govern a table type's identity column, but
/// <see cref="IgnoreColumnOrder"/> is tables-only (a table type marshals its columns positionally as a
/// TVP, so its column order is always significant).
/// </summary>
[Flags]
public enum TableNormalization
{
	/// <summary>Full fidelity — every table-level facet participates in the hash.</summary>
	Strict = 0,

	/// <summary>
	/// Compare a table's columns by name (plus their full attribute set) regardless of position, so two
	/// tables with the same columns in a different order compare equal. Tables only — table types stay
	/// order-sensitive.
	/// </summary>
	IgnoreColumnOrder = 1 << 0,

	/// <summary>Neutralize the identity column's seed and increment (IDENTITY(1000,5) ≡ IDENTITY(1,1)).</summary>
	IgnoreIdentitySeed = 1 << 1,

	/// <summary>Neutralize the identity column's NOT FOR REPLICATION flag.</summary>
	IgnoreIdentityNotForReplication = 1 << 2,

	/// <summary>Neutralize a system-versioned table's finite history retention policy (period + unit).</summary>
	IgnoreTemporalRetention = 1 << 3,

	/// <summary>Structural comparison: ignore table column order. Matches the existing Structural preset.</summary>
	Structural = IgnoreColumnOrder,
}

/// <summary>
/// Normalization of column-level attributes shared by tables and table types (collation, ANSI
/// padding, dynamic data masking). Type/length/precision/scale/nullability, computed-ness, storage
/// markers (sparse/rowguid/filestream), encryption and XML typing always participate.
/// </summary>
[Flags]
public enum ColumnNormalization
{
	/// <summary>Full fidelity — every captured column attribute participates in the hash.</summary>
	Strict = 0,

	/// <summary>
	/// Neutralize a column's collation, so columns that differ only by inherited server/database default
	/// collation across environments compare equal.
	/// </summary>
	IgnoreCollation = 1 << 0,

	/// <summary>Neutralize the ANSI_PADDING (is_ansi_padded) storage semantics flag.</summary>
	IgnoreAnsiPadding = 1 << 1,

	/// <summary>Neutralize Dynamic Data Masking state (is_masked / masking function).</summary>
	IgnoreDynamicDataMasking = 1 << 2,

	/// <summary>Structural comparison: column attributes are compared exactly (matches the existing preset).</summary>
	Structural = Strict,
}

/// <summary>
/// Normalization of indexes (<c>sys.indexes</c>): names, clustering placement, key sort order, and the
/// physical storage / locking options. Uniqueness/PK-ness, key and included columns, filter predicate
/// and IGNORE_DUP_KEY always participate.
/// </summary>
[Flags]
public enum IndexNormalization
{
	/// <summary>Full fidelity — every captured index attribute participates in the hash.</summary>
	Strict = 0,

	/// <summary>Drop index names entirely — only the index definition matters. Wins over <see cref="NormalizeAutoGeneratedNames"/>.</summary>
	IgnoreNames = 1 << 0,

	/// <summary>
	/// Collapse auto-generated index names (SQL Server system names and GUID-suffixed missing-index names,
	/// via the name-shape heuristic) to a common sentinel; explicit names still compare exactly.
	/// </summary>
	NormalizeAutoGeneratedNames = 1 << 1,

	/// <summary>Normalize rowstore CLUSTERED ≡ NONCLUSTERED placement (the columnstore distinction is preserved).</summary>
	NormalizeClustering = 1 << 2,

	/// <summary>Drop each key column's ASC/DESC direction (key column order itself stays significant).</summary>
	IgnoreSortOrder = 1 << 3,

	/// <summary>Neutralize the FILLFACTOR storage option.</summary>
	IgnoreFillFactor = 1 << 4,

	/// <summary>Neutralize the PAD_INDEX storage option.</summary>
	IgnorePadIndex = 1 << 5,

	/// <summary>Neutralize the ALLOW_ROW_LOCKS / ALLOW_PAGE_LOCKS locking options.</summary>
	IgnoreLockOptions = 1 << 6,

	/// <summary>Neutralize a disabled index's is_disabled flag.</summary>
	IgnoreDisabled = 1 << 7,

	/// <summary>
	/// Structural comparison: ignore index names, normalize clustering placement, and ignore key sort
	/// order. Matches the existing Structural preset (physical storage / lock / disabled bits are not
	/// folded in here — that is a presets-round decision).
	/// </summary>
	Structural = IgnoreNames | NormalizeClustering | IgnoreSortOrder,
}

/// <summary>
/// Normalization of constraints (PRIMARY KEY / UNIQUE / FOREIGN KEY / CHECK / DEFAULT): names and the
/// FK/CHECK enforcement state. The constraint definition (type, key columns, referenced table/columns,
/// referential actions, predicate/default expression) always participates.
/// </summary>
[Flags]
public enum ConstraintNormalization
{
	/// <summary>Full fidelity — constraint names and enforcement state participate in the hash.</summary>
	Strict = 0,

	/// <summary>Drop constraint names entirely — only the definition matters. Wins over <see cref="NormalizeAutoGeneratedNames"/>.</summary>
	IgnoreNames = 1 << 0,

	/// <summary>
	/// Collapse auto-generated constraint names to a common sentinel; explicitly-named constraints still
	/// compare exactly. A name counts as auto-generated when the authoritative <c>is_system_named</c>
	/// catalog flag is set <em>or</em> the name matches the SQL Server generated shape
	/// (<c>PK__Table__&lt;hex&gt;</c> etc.). The shape check is what keeps comparison stable across a
	/// script-out / DACPAC redeploy: <c>is_system_named</c> is recorded from whether the creating
	/// statement supplied a name, so recreating a system-named constraint from a script that emits its
	/// literal name flips the flag to 0 even though the name is still generated.
	/// </summary>
	NormalizeAutoGeneratedNames = 1 << 1,

	/// <summary>Neutralize a FOREIGN KEY / CHECK constraint's disabled (NOCHECK) state.</summary>
	IgnoreDisabled = 1 << 2,

	/// <summary>Neutralize a FOREIGN KEY / CHECK constraint's untrusted (is_not_trusted) state — the classic post-bulk-load drift.</summary>
	IgnoreTrust = 1 << 3,

	/// <summary>Neutralize a FOREIGN KEY / CHECK constraint's NOT FOR REPLICATION flag.</summary>
	IgnoreNotForReplication = 1 << 4,

	/// <summary>Structural comparison: ignore constraint names. Matches the existing Structural preset.</summary>
	Structural = IgnoreNames,
}

/// <summary>
/// Normalization of programmable modules (stored procedures): body text and the CREATE-time SET
/// options. The procedure name and parameter signatures always participate.
/// </summary>
[Flags]
public enum ModuleNormalization
{
	/// <summary>Full fidelity — the procedure body hash and SET options participate.</summary>
	Strict = 0,

	/// <summary>Drop the procedure body definition hash — only the name and parameter signatures matter.</summary>
	IgnoreBodyText = 1 << 0,

	/// <summary>Neutralize the CREATE-time ANSI_NULLS / QUOTED_IDENTIFIER SET options.</summary>
	IgnoreSetOptions = 1 << 1,

	/// <summary>Structural comparison: module body and SET options are compared exactly (matches the existing preset).</summary>
	Structural = Strict,
}
