using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;

namespace zachtbeer.SqlSchemaHasher;

/// <summary>
/// Computes deterministic SHA256 hashes from schema metadata for comparison.
/// Uses IncrementalHash for memory-efficient streaming.
/// All object names are schema-qualified to correctly distinguish objects in different schemas.
/// </summary>
public sealed class SchemaHashCalculator
{
    private readonly SchemaHashOptions _options;

    /// <summary>
    /// Creates a new hash calculator with <see cref="SchemaHashOptions.Default"/>.
    /// </summary>
    public SchemaHashCalculator() : this(SchemaHashOptions.Default)
    {
    }

    /// <summary>
    /// Creates a new hash calculator with the specified options.
    /// </summary>
    /// <param name="options">Options controlling normalization behavior. Pass null for <see cref="SchemaHashOptions.Default"/>.</param>
    public SchemaHashCalculator(SchemaHashOptions options)
    {
        _options = options ?? SchemaHashOptions.Default;
    }

    /// <summary>
    /// Computes a deterministic SHA256 hash from the schema metadata.
    /// All elements are sorted by their fully-qualified names (schema.name) before hashing to ensure determinism.
    /// </summary>
    /// <param name="schema">The schema metadata to hash.</param>
    /// <returns>64-character lowercase hex string representing the SHA256 hash.</returns>
    public string ComputeHash(SchemaMetadata schema)
    {
        using var hasher = IncrementalHash.CreateHash(HashAlgorithmName.SHA256);

        // Hash tables in sorted order by fully-qualified name
        foreach (var table in schema.Tables.OrderBy(t => t.SchemaName).ThenBy(t => t.Name))
        {
            HashTable(hasher, table);
        }

        // Hash stored procedures in sorted order by fully-qualified name
        foreach (var proc in schema.StoredProcedures.OrderBy(p => p.SchemaName).ThenBy(p => p.Name))
        {
            HashStoredProcedure(hasher, proc);
        }

        // Hash user-defined table types in sorted order by fully-qualified name
        foreach (var udt in schema.UserDefinedTableTypes.OrderBy(u => u.SchemaName).ThenBy(u => u.Name))
        {
            HashUserDefinedTableType(hasher, udt);
        }

        var hash = hasher.GetHashAndReset();
        return Convert.ToHexString(hash).ToLowerInvariant();
    }

    private void HashTable(IncrementalHash hasher, TableSchema table)
    {
        // Marker to separate tables
        AppendString(hasher, "TABLE:");
        // Include schema name to distinguish dbo.Employees from reporting.Employees
        AppendString(hasher, table.SchemaName);
        AppendString(hasher, table.Name);

        // Identity column
        if (!string.IsNullOrEmpty(table.IdentityColumn))
        {
            AppendString(hasher, "IDENTITY:");
            AppendString(hasher, table.IdentityColumn);
        }

        // Columns in sorted order
        foreach (var column in table.Columns.OrderBy(c => c.Name))
        {
            HashColumn(hasher, column);
        }

        // Indexes in sorted order (by keys then name)
        foreach (var index in table.Indexes.OrderBy(i => i.Keys).ThenBy(i => i.Name))
        {
            HashIndex(hasher, index);
        }

        // Constraints in sorted order (by keys then type)
        foreach (var constraint in table.Constraints.OrderBy(c => c.Keys).ThenBy(c => c.Type))
        {
            HashConstraint(hasher, constraint);
        }
    }

    private void HashColumn(IncrementalHash hasher, ColumnSchema column)
    {
        AppendString(hasher, "COL:");
        AppendString(hasher, column.Name);
        AppendString(hasher, column.DataType);
        AppendInt(hasher, column.MaxLength);
        AppendInt(hasher, column.Precision);
        AppendInt(hasher, column.Scale);
        AppendBool(hasher, column.IsNullable);
    }

    private void HashIndex(IncrementalHash hasher, IndexSchema index)
    {
        AppendString(hasher, "IDX:");

        // Use normalized or exact name based on options
        string indexName = _options.NormalizeAutoGeneratedIndexNames
            ? NormalizeAutoGeneratedName(index.Name)
            : index.Name;

        AppendString(hasher, indexName);

        // Optionally normalize clustering type
        string description = _options.NormalizeClusteringType
            ? NormalizeClusteringDescription(index.Description)
            : index.Description;

        AppendString(hasher, description);
        AppendString(hasher, index.Keys ?? string.Empty);
    }

    private void HashConstraint(IncrementalHash hasher, ConstraintSchema constraint)
    {
        AppendString(hasher, "CONST:");
        AppendString(hasher, constraint.Type);
        AppendString(hasher, constraint.Keys ?? string.Empty);
    }

    private void HashStoredProcedure(IncrementalHash hasher, StoredProcedureSchema proc)
    {
        AppendString(hasher, "PROC:");
        // Include schema name to distinguish dbo.GetEmployee from sales.GetEmployee
        AppendString(hasher, proc.SchemaName);
        AppendString(hasher, proc.Name);

        // Optionally include definition hash to detect body changes
        if (_options.IncludeStoredProcedureText)
        {
            AppendString(hasher, "DEFHASH:");
            AppendString(hasher, proc.DefinitionHash);
        }

        foreach (var param in proc.Parameters)
        {
            HashParameter(hasher, param);
        }
    }

    private void HashParameter(IncrementalHash hasher, ParameterSchema param)
    {
        AppendString(hasher, "PARAM:");
        AppendString(hasher, param.Name);
        AppendString(hasher, param.Type);
        AppendInt(hasher, param.MaxLength);
        AppendInt(hasher, param.Precision);
        AppendInt(hasher, param.Scale);
        AppendBool(hasher, param.IsNullable);
    }

    private void HashUserDefinedTableType(IncrementalHash hasher, UserDefinedTableTypeSchema udt)
    {
        AppendString(hasher, "UDT:");
        // Include schema name to distinguish types in different schemas
        AppendString(hasher, udt.SchemaName);
        AppendString(hasher, udt.Name);

        foreach (var column in udt.Columns.OrderBy(c => c.Name))
        {
            HashColumn(hasher, column);
        }
    }

    private static string NormalizeClusteringDescription(string description)
    {
        return Regex.Replace(description, @"(?:non-?)?clustered", "x-clustered", RegexOptions.IgnoreCase);
    }

    /// <summary>
    /// Normalizes auto-generated index/constraint names by removing GUID suffixes.
    /// e.g., 'nci_wi_Asset_EF8A0893C0DB8B0FC4AD9EABBE187744' -> 'nci_wi_Asset'
    /// </summary>
    private static string NormalizeAutoGeneratedName(string name)
    {
        if (string.IsNullOrEmpty(name) || name.Length < 12)
            return name;

        var parts = name.Split('_', StringSplitOptions.RemoveEmptyEntries);
        if (parts.Length < 3)
            return name;

        var lastPart = parts[^1];
        if (string.IsNullOrWhiteSpace(lastPart))
            return name;

        // Check if the last part looks like hexadecimal
        if (!lastPart.All(c => (c >= '0' && c <= '9') || (c >= 'a' && c <= 'f') || (c >= 'A' && c <= 'F')))
            return name;

        // Check if the last part has a multiple of 8 characters (typical GUID suffix)
        if (lastPart.Length % 8 != 0)
            return name;

        return string.Join('_', parts[..^1]);
    }

    private static void AppendString(IncrementalHash hasher, string value)
    {
        var bytes = Encoding.UTF8.GetBytes(value);
        // Prefix with length to avoid collisions like "AB" + "C" vs "A" + "BC"
        hasher.AppendData(BitConverter.GetBytes(bytes.Length));
        hasher.AppendData(bytes);
    }

    private static void AppendInt(IncrementalHash hasher, int value)
    {
        hasher.AppendData(BitConverter.GetBytes(value));
    }

    private static void AppendBool(IncrementalHash hasher, bool value)
    {
        hasher.AppendData(BitConverter.GetBytes(value));
    }
}
