namespace zachtbeer.SqlSchemaHasher;

/// <summary>
/// Simple static API for computing deterministic schema hashes from SQL Server databases.
/// </summary>
public static class SqlSchemaHash
{
    /// <summary>
    /// Computes a deterministic base64-encoded SHA256 hash of the database schema.
    /// </summary>
    /// <param name="connectionString">SQL Server connection string.</param>
    /// <returns>Base64-encoded SHA256 hash of the schema.</returns>
    /// <example>
    /// <code>
    /// var hash = await SqlSchemaHash.GetHashAsync("Server=localhost;Database=MyDb;...");
    /// // Returns: "dGhpcyBpcyBhIGhhc2g..."
    /// </code>
    /// </example>
    public static async Task<string> GetHashAsync(string connectionString)
    {
        return await GetHashAsync(connectionString, SchemaHashOptions.Default);
    }

    /// <summary>
    /// Computes a deterministic base64-encoded SHA256 hash of the database schema with custom options.
    /// </summary>
    /// <param name="connectionString">SQL Server connection string.</param>
    /// <param name="options">Options for extraction and hash calculation (schema filter, index name normalization, etc.).</param>
    /// <returns>Base64-encoded SHA256 hash of the schema.</returns>
    /// <example>
    /// <code>
    /// var options = new SchemaHashOptions
    /// {
    ///     SchemaFilter = "dbo",  // Only hash objects in the dbo schema
    ///     NormalizeAutoGeneratedIndexNames = true
    /// };
    /// var hash = await SqlSchemaHash.GetHashAsync("Server=localhost;Database=MyDb;...", options);
    /// </code>
    /// </example>
    public static async Task<string> GetHashAsync(string connectionString, SchemaHashOptions options)
    {
        var extractor = new SchemaExtractor();
        var calculator = new SchemaHashCalculator(options);

        var schema = await extractor.ExtractSchemaAsync(connectionString, options);
        var hexHash = calculator.ComputeHash(schema);

        // Convert hex to bytes, then to base64
        var hashBytes = Convert.FromHexString(hexHash);
        return Convert.ToBase64String(hashBytes);
    }

    /// <summary>
    /// Extracts detailed schema metadata from a SQL Server database.
    /// Use this if you need access to the raw schema information.
    /// </summary>
    /// <param name="connectionString">SQL Server connection string.</param>
    /// <returns>Schema metadata containing tables, stored procedures, and user-defined types.</returns>
    public static async Task<SchemaMetadata> ExtractSchemaAsync(string connectionString)
    {
        return await ExtractSchemaAsync(connectionString, null);
    }

    /// <summary>
    /// Extracts detailed schema metadata from a SQL Server database with optional filtering.
    /// Use this if you need access to the raw schema information.
    /// </summary>
    /// <param name="connectionString">SQL Server connection string.</param>
    /// <param name="options">Options for extraction (e.g., schema filter). Pass null for defaults.</param>
    /// <returns>Schema metadata containing tables, stored procedures, and user-defined types.</returns>
    public static async Task<SchemaMetadata> ExtractSchemaAsync(string connectionString, SchemaHashOptions? options)
    {
        var extractor = new SchemaExtractor();
        return await extractor.ExtractSchemaAsync(connectionString, options);
    }

    /// <summary>
    /// Computes a base64-encoded hash from pre-extracted schema metadata.
    /// Useful when you already have schema metadata and want to compute multiple hashes with different options.
    /// </summary>
    /// <param name="schema">Previously extracted schema metadata.</param>
    /// <param name="options">Options for hash calculation.</param>
    /// <returns>Base64-encoded SHA256 hash of the schema.</returns>
    public static string ComputeHash(SchemaMetadata schema, SchemaHashOptions? options = null)
    {
        var calculator = new SchemaHashCalculator(options ?? SchemaHashOptions.Default);
        var hexHash = calculator.ComputeHash(schema);
        var hashBytes = Convert.FromHexString(hexHash);
        return Convert.ToBase64String(hashBytes);
    }
}
