using zachtbeer.SqlSchemaHasher;
using Shouldly;

namespace SqlSchemaHash.UnitTests.Determinism;

/// <summary>
/// DB-free tests for the anonymous-temporal-history-table normalization in SchemaHashCalculator
/// (EffectiveTableName / HistoryIndexNameRewrite): an auto-named history table's raw
/// MSSQL_TemporalHistoryFor_&lt;object_id&gt; name (and its auto-created ix_MSSQL_TemporalHistoryFor_&lt;id&gt;
/// index) embeds a per-database object_id, so it must be normalized to a name derived from the
/// versioned parent instead — while an explicitly-named history table stays exact. Container-dependent
/// end-to-end coverage lives in the integration suite's Fidelity/TemporalHistoryTableFidelityTests.
/// </summary>
[TestClass]
public class TemporalHistoryTableNormalizationTests
{
    [TestMethod]
    public void AnonymousHistoryTable_DifferentRawObjectIdSuffix_SameVersionedParent_HashesEqual()
    {
        var table1 = HistoryTable("MSSQL_TemporalHistoryFor_889838603", "dbo", "Account");
        var table2 = HistoryTable("MSSQL_TemporalHistoryFor_1573551412", "dbo", "Account");

        HashOf(table1).ShouldBe(HashOf(table2), "Two anonymous history tables for the same versioned parent must hash identically regardless of their raw object_id-derived names");
    }

    [TestMethod]
    public void AnonymousHistoryTable_DifferentVersionedParent_HashesDiffer()
    {
        var table1 = HistoryTable("MSSQL_TemporalHistoryFor_889838603", "dbo", "Account");
        var table2 = HistoryTable("MSSQL_TemporalHistoryFor_889838603", "dbo", "Widget");

        HashOf(table1).ShouldNotBe(HashOf(table2), "Moving SYSTEM_VERSIONING to a different parent is a genuine schema change and must change the hash");
    }

    [TestMethod]
    public void ExplicitlyNamedHistoryTable_IsNotNormalized_DifferentNamesHashDiffer()
    {
        var table1 = HistoryTable("Account_History", "dbo", "Account");
        var table2 = HistoryTable("Account_Archive", "dbo", "Account");

        HashOf(table1).ShouldNotBe(HashOf(table2), "An explicitly-chosen history table name is real schema and must not be normalized away");
    }

    [TestMethod]
    public void AnonymousHistoryIndex_DifferentRawObjectIdSuffix_SameVersionedParent_HashesEqual()
    {
        var table1 = HistoryTable("MSSQL_TemporalHistoryFor_889838603", "dbo", "Account") with
        {
            Indexes = new List<IndexSchema> { new("ix_MSSQL_TemporalHistoryFor_889838603", "CLUSTERED", false, false, false, false, false, new List<IndexKeyColumn> { new("ValidFrom", false) }, new List<string>()) }
        };
        var table2 = HistoryTable("MSSQL_TemporalHistoryFor_1573551412", "dbo", "Account") with
        {
            Indexes = new List<IndexSchema> { new("ix_MSSQL_TemporalHistoryFor_1573551412", "CLUSTERED", false, false, false, false, false, new List<IndexKeyColumn> { new("ValidFrom", false) }, new List<string>()) }
        };

        HashOf(table1).ShouldBe(HashOf(table2), "The auto-created history index's raw object_id-derived name must be normalized the same way as the table's own name");
    }

    [TestMethod]
    public void AnonymousHistoryTable_ExtraIndex_StillChangesHash()
    {
        var table1 = HistoryTable("MSSQL_TemporalHistoryFor_889838603", "dbo", "Account") with
        {
            Indexes = new List<IndexSchema> { new("ix_MSSQL_TemporalHistoryFor_889838603", "CLUSTERED", false, false, false, false, false, new List<IndexKeyColumn> { new("ValidFrom", false) }, new List<string>()) }
        };
        var table2 = HistoryTable("MSSQL_TemporalHistoryFor_1573551412", "dbo", "Account") with
        {
            Indexes = new List<IndexSchema>
            {
                new("ix_MSSQL_TemporalHistoryFor_1573551412", "CLUSTERED", false, false, false, false, false, new List<IndexKeyColumn> { new("ValidFrom", false) }, new List<string>()),
                new("IX_History_ValidFrom", "NONCLUSTERED", false, false, false, false, false, new List<IndexKeyColumn> { new("ValidFrom", false) }, new List<string>()),
            }
        };

        HashOf(table1).ShouldNotBe(HashOf(table2), "A genuinely extra, user-added index on the history table must still change the hash after the auto-created index's own identity is normalized");
    }

    [TestMethod]
    public void OrdinaryTable_NameShapedLikeAutoGeneratedHistoryTable_IsNotNormalized()
    {
        // Guards EffectiveTableName's TemporalType gate: a plain table that happens to share the
        // MSSQL_TemporalHistoryFor_<n> shape (not itself a history table) must hash by its raw name.
        var table1 = new TableSchema("dbo", "MSSQL_TemporalHistoryFor_1", new List<ColumnSchema>(), new List<IndexSchema>(), new List<KeyConstraintSchema>(), new List<ForeignKeyConstraintSchema>(), new List<CheckConstraintSchema>(), new List<DefaultConstraintSchema>(), null);
        var table2 = new TableSchema("dbo", "MSSQL_TemporalHistoryFor_2", new List<ColumnSchema>(), new List<IndexSchema>(), new List<KeyConstraintSchema>(), new List<ForeignKeyConstraintSchema>(), new List<CheckConstraintSchema>(), new List<DefaultConstraintSchema>(), null);

        HashOf(table1).ShouldNotBe(HashOf(table2), "Without TemporalType == HISTORY_TABLE, the name-shape match alone must not trigger normalization");
    }

    private static TableSchema HistoryTable(string name, string versionedParentSchema, string versionedParentName) =>
        new("dbo", name, new List<ColumnSchema>(), new List<IndexSchema>(), new List<KeyConstraintSchema>(), new List<ForeignKeyConstraintSchema>(), new List<CheckConstraintSchema>(), new List<DefaultConstraintSchema>(), null, TemporalType: "HISTORY_TABLE", VersionedParentSchema: versionedParentSchema, VersionedParentName: versionedParentName);

    private static string HashOf(TableSchema table) =>
        new SchemaHashCalculator().ComputeHash(new SchemaMetadata(new List<TableSchema> { table }, new List<StoredProcedureSchema>(), new List<UserDefinedTableTypeSchema>(), new List<ViewSchema>(), new List<FunctionSchema>(), new List<TriggerSchema>(), new List<SequenceSchema>(), new List<SynonymSchema>(), new List<ExtendedPropertySchema>()));
}
